module.exports = {
  BASE_URL: 'http://localhost:5000',
  // BASE_URL: 'https://readingapp-d5944320053c.herokuapp.com',
  VERIFY_EMAIL_TIME: '3h',
  ACCESS_TOKEN_TIME: '5h',

  // Settings.
  DEFAULT_TEXT_SIZE: 14,
  THEME: {
    DEFAULT: 'Default',
    DARK: 'Dark',
    BLACK_AND_WHITE: 'BlackAndWhite',
    SAPPHIRE: 'Sapphire',
    EASY_OCEAN: 'EasyOcean',
  },
  AYA_NUMBER_FORMAT: {
    BEFORE: 'before',
    AFTER: 'after',
  },
  DISPLAY_TYPE: {
    ONLY_TRNSLATION: 'only_translation',
    SPLIT_PANEL: 'split_panel',
    VERSE_BY_VERSE: 'verse_by_verse',
  },
  READING_CONTROLS_TYPE: {
    LEFT_HANDED: 'left_handed',
    RIGHT_HANDED: 'right_handed',
  },
  REFERENCE_LANGUAGE: {
    ARABIC: 'ar',
    ENGLISH: 'en',
  },
  READING_LANGUAGE: {
    ARABIC: 'ar',
    ENGLISH: 'en',
  },
  KEEP_ENGLISH: false,
  APP_LANGUAGE: {
    ARABIC: 'ar',
    ENGLISH: 'en',
  },
  PAGES_CONTROLS_TYPE: {
    RIGTH_TO_LEFT: 'right_to_left',
    LEFT_TO_RIGHT: 'left_to_right',
  },
  SOUND_LANGUAGE: {
    ORIGINAL: 'ar',
    TRANSLATION: 'en',
    OTHER: 'other',
  },

  LANGUAGE_CODE_TABLES: [
    { language: 'Abkhazian', code: 'ab' },
    { language: 'Afar', code: 'aa' },
    { language: 'Afrikaans', code: 'af' },
    { language: 'Akan', code: 'ak' },
    { language: 'Albanian', code: 'sq' },
    { language: 'Amharic', code: 'am' },
    { language: 'Arabic', code: 'ar' },
    { language: 'Aragonese', code: 'an' },
    { language: 'Armenian', code: 'hy' },
    { language: 'Assamese', code: 'as' },
    { language: 'Avaric', code: 'av' },
    { language: 'Aymara', code: 'ay' },
    { language: 'Azerbaijani', code: 'az' },
    { language: 'Bashkir', code: 'ba' },
    { language: 'Basque', code: 'eu' },
    { language: 'Belarusian', code: 'be' },
    { language: 'Bengali', code: 'bn' },
    { language: 'Bihari languages', code: 'bh' },
    { language: 'Bislama', code: 'bi' },
    { language: 'Bosnian', code: 'bs' },
    { language: 'Breton', code: 'br' },
    { language: 'Bulgarian', code: 'bg' },
    { language: 'Burmese', code: 'my' },
    { language: 'Catalan', code: 'ca' },
    { language: 'Chamorro', code: 'ch' },
    { language: 'Chechen', code: 'ce' },
    { language: 'Chichewa', code: 'ny' },
    { language: 'Chinese', code: 'zh' },
    { language: 'Chuvash', code: 'cv' },
    { language: 'Cornish', code: 'kw' },
    { language: 'Corsican', code: 'co' },
    { language: 'Cree', code: 'cr' },
    { language: 'Croatian', code: 'hr' },
    { language: 'Czech', code: 'cs' },
    { language: 'Danish', code: 'da' },
    { language: 'Divehi', code: 'dv' },
    { language: 'Dutch', code: 'nl' },
    { language: 'Dzongkha', code: 'dz' },
    { language: 'English', code: 'en' },
    { language: 'Esperanto', code: 'eo' },
    { language: 'Estonian', code: 'et' },
    { language: 'Ewe', code: 'ee' },
    { language: 'Fijian', code: 'fj' },
    { language: 'Finnish', code: 'fi' },
    { language: 'French', code: 'fr' },
    { language: 'Fulah', code: 'ff' },
    { language: 'Georgian', code: 'ka' },
    { language: 'German', code: 'de' },
    { language: 'Greek', code: 'el' },
    { language: 'Guarani', code: 'gn' },
    { language: 'Gujarati', code: 'gu' },
    { language: 'Haitian Creole', code: 'ht' },
    { language: 'Hausa', code: 'ha' },
    { language: 'Hebrew', code: 'he' },
    { language: 'Hindi', code: 'hi' },
    { language: 'Hmong', code: 'hm' },
    { language: 'Hungarian', code: 'hu' },
    { language: 'Icelandic', code: 'is' },
    { language: 'Igbo', code: 'ig' },
    { language: 'Indonesian', code: 'id' },
    { language: 'Inuktitut', code: 'iu' },
    { language: 'Irish', code: 'ga' },
    { language: 'Italian', code: 'it' },
    { language: 'Japanese', code: 'ja' },
    { language: 'Javanese', code: 'jv' },
    { language: 'Kalaallisut', code: 'kl' },
    { language: 'Kannada', code: 'kn' },
    { language: 'Kanuri', code: 'kr' },
    { language: 'Kashmiri', code: 'ks' },
    { language: 'Kazakh', code: 'kk' },
    { language: 'Khmer', code: 'km' },
    { language: 'Kinyarwanda', code: 'rw' },
    { language: 'Kirghiz', code: 'ky' },
    { language: 'Korean', code: 'ko' },
    { language: 'Kurdish', code: 'ku' },
    { language: 'Kyrgyz', code: 'ky' },
    { language: 'Lao', code: 'lo' },
    { language: 'Latin', code: 'la' },
    { language: 'Latvian', code: 'lv' },
    { language: 'Lingala', code: 'ln' },
    { language: 'Lithuanian', code: 'lt' },
    { language: 'Luxembourgish', code: 'lb' },
    { language: 'Macedonian', code: 'mk' },
    { language: 'Malagasy', code: 'mg' },
    { language: 'Malay', code: 'ms' },
    { language: 'Malayalam', code: 'ml' },
    { language: 'Maltese', code: 'mt' },
    { language: 'Maori', code: 'mi' },
    { language: 'Marathi', code: 'mr' },
    { language: 'Mongolian', code: 'mn' },
    { language: 'Nepali', code: 'ne' },
    { language: 'Norwegian', code: 'no' },
    { language: 'Nyanja', code: 'ny' },
    { language: 'Occitan', code: 'oc' },
    { language: 'Oromo', code: 'om' },
    { language: 'Ossetian', code: 'os' },
    { language: 'Panjabi', code: 'pa' },
    { language: 'Pashto', code: 'ps' },
    { language: 'Persian', code: 'fa' },
    { language: 'Polish', code: 'pl' },
    { language: 'Portuguese', code: 'pt' },
    { language: 'Quechua', code: 'qu' },
    { language: 'Romanian', code: 'ro' },
    { language: 'Russian', code: 'ru' },
    { language: 'Samoan', code: 'sm' },
    { language: 'Scots Gaelic', code: 'gd' },
    { language: 'Serbian', code: 'sr' },
    { language: 'Shona', code: 'sn' },
    { language: 'Sindhi', code: 'sd' },
    { language: 'Sinhalese', code: 'si' },
    { language: 'Slovak', code: 'sk' },
    { language: 'Slovenian', code: 'sl' },
    { language: 'Somali', code: 'so' },
    { language: 'Spanish', code: 'es' },
    { language: 'Sundanese', code: 'su' },
    { language: 'Swahili', code: 'sw' },
    { language: 'Swedish', code: 'sv' },
    { language: 'Tagalog', code: 'tlg' },
    { language: 'Tajik', code: 'tg' },
    { language: 'Tamil', code: 'ta' },
    { language: 'Tatar', code: 'tt' },
    { language: 'Telugu', code: 'te' },
    { language: 'Thai', code: 'th' },
    { language: 'Tigrinya', code: 'ti' },
    { language: 'Tonga', code: 'to' },
    { language: 'Turkish', code: 'tr' },
    { language: 'Turkmen', code: 'tk' },
    { language: 'Twi', code: 'tw' },
    { language: 'Ukrainian', code: 'uk' },
    { language: 'Urdu', code: 'ur' },
    { language: 'Uyghur', code: 'ug' },
    { language: 'Uzbek', code: 'uz' },
    { language: 'Vietnamese', code: 'vi' },
    { language: 'Welsh', code: 'cy' },
    { language: 'Xhosa', code: 'xh' },
    { language: 'Yiddish', code: 'yi' },
    { language: 'Yoruba', code: 'yo' },
    { language: 'Zulu', code: 'zu' },
  ],
};
