export default {
  SET_BOOK: 'SET_BOOK',
  SET_BOOKINFOS: 'SET_BOOKINFOS',
  ADD_BOOKINFO: 'ADD_BOOKINFO',
  REMOVE_BOOKINFO: 'REMOVE_BOOKINFO',
  SET_SUBBOOKINFO: 'SET_SUBBOOKINFO',
  ADD_SUBBOOKINFO: 'ADD_SUBBOOKINFO',
  REMOVE_SUBBOOKINFO: 'REMOVE_SUBBOOKINFO',
  ADD_SUBBOOK: 'ADD_SUBBOOK',
  ADD_CHAPTERINFO: 'ADD_CHAPTERINFO',
  UPDATE_CHAPTERINFOS: 'UPDATE_CHAPTERINFOS',

  SET_JOURNEY_BOOK: 'SET_JOURNEY_BOOK',

  SET_CURRENT_LANGUAGE: 'SET_CURRENT_LANGUAGE',

  RESET_BOOK: 'RESET_BOOK',
  RESET_JOURNEY: 'RESET_JOURNEY',
}