export default {
  SET_BOOKINFOS: 'SET_BOOKINFOS',
  ADD_BOOKINFO: 'ADD_BOOKINFO',
  REMOVE_BOOKINFO: 'REMOVE_BOOKINFO',
  SET_SUBBOOKINFO: 'SET_SUBBOOKINFO',
  ADD_SUBBOOKINFO: 'ADD_SUBBOOKINFO',
  REMOVE_SUBBOOKINFO: 'REMOVE_SUBBOOKINFO',
  ADD_SUBBOOK: 'ADD_SUBBOOK',
  ADD_CHAPTERINFO: 'ADD_CHAPTERINFO',

  SET_CURRENT_LANGUAGE: 'SET_CURRENT_LANGUAGE',

  RESET_BOOK: 'RESET_BOOK',
}