export default {
  SET_JOURNEY_BOOK: 'SET_JOURNEY_BOOK',
  SET_JOURNEY_PARENT_ID: 'SET_PARENT_ID',
  SET_JOURNEY_IMAGE: 'SET_JOURNEY_IMAGE',
  SET_JOUREY_PARENT_TITLE: 'SET_JOURNEY_PARENT_TITLE',
  
  RESET_JOURNEY: 'RESET_JOURNEY',
}

