export default {
  SET_JOURNEY_BOOK: 'SET_JOURNEY_BOOK',
  SET_JOURNEY_BOOK_MARK_IMAGE: 'SET_JOURNEY_BOOK_MARK_IMAGE',
  SET_JOURNEY_PARENT_ID: 'SET_PARENT_ID',
  SET_JOURNEY_IMAGE: 'SET_JOURNEY_IMAGE',
  SET_JOUREY_PARENT_TITLE: 'SET_JOURNEY_PARENT_TITLE',
  SET_JOURNEY_DEPTH: 'SET_JOURNEY_DEPTH',

  UPDATE_JOURNEY_CARDS: 'UPDATE_JOURNEY_CARDS',
  
  RESET_JOURNEY: 'RESET_JOURNEY',
}

