export default {
  SET_APP_TEXT_PAGES: 'SET_APP_TEXT_PAGES',
  UPDATE_APP_TEXT_PAGES: 'UPDATE_APP_TEXT_PAGES',
  SET_CURRENT_AUDIO_HANDLER: 'SET_CURRENT_AUDIO_HANDLER',

  RESET_APP_TEXT_PAGES: 'RESET_APP_TEXT_PAGES',
}
